[package]
name = "odo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pam = "*"
users = "*"
serde = "*"
serde_derive = "*"
toml = "*"
console = "*"
etc-passwd = "*"